# Generated by Django 4.0.1 on 2022-04-11 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='Created_By', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='Modified_By', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, db_column='Modified_On', null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='Deleted_By', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now_add=True, db_column='Deleted_On')),
                ('name', models.CharField(db_column='Name', max_length=255, unique=True)),
                ('code', models.SlugField(db_column='Code', default='')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('access_level', models.IntegerField(choices=[(1000, 'Chief Executive Officer'), (700, 'Team Manager'), (300, 'Software Engineer')], db_column='AccessLevel', default='software-engineer')),
            ],
            options={
                'db_table': 'TaskTrackingRoles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_by', models.BigIntegerField(blank=True, db_column='Created_By', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='Modified_By', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, db_column='Modified_On', null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='Deleted_By', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now_add=True, db_column='Deleted_On')),
                ('first_name', models.CharField(db_column='FirstName', max_length=255, null=True)),
                ('last_name', models.CharField(db_column='LastName', max_length=255, null=True)),
                ('email', models.EmailField(db_column='Email', default='', max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True, help_text='Designates whether this user should be treated as active')),
                ('is_staff', models.BooleanField(db_column='IsStaff', default=True, help_text='Designates whether the user can log into this admin site')),
                ('is_approved', models.BooleanField(db_column='IsApproved', default=False, help_text='Designates whether this user is approved or not')),
                ('is_superuser', models.BooleanField(db_column='IsSuperUser', default=False, help_text='Designates whether this user is the superuser or not')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('role', models.ForeignKey(blank=True, db_column='RoleID', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
