# Generated by Django 4.0.1 on 2022-04-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='Created_By', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='Modified_By', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, db_column='Modified_On', null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='Deleted_By', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now_add=True, db_column='Deleted_On')),
                ('name', models.CharField(db_column='Name', default='Pending', max_length=255)),
            ],
            options={
                'db_table': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='Created_By', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='Modified_By', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, db_column='Modified_On', null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, db_column='Deleted_By', default=0, null=True)),
                ('deleted_on', models.DateTimeField(auto_now_add=True, db_column='Deleted_On')),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('description', models.TextField(db_column='Description')),
                ('time_estimation', models.TimeField()),
            ],
            options={
                'db_table': 'Tasks',
            },
        ),
    ]
